version: '3'

services:
  mongo:
    image: mongo
    container_name: user-mongo-db
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: naovoufalar
      MONGO_INITDB_DATABASE: userdb
  mongoexpress:
    image: mongo-express
    ports:
        - "8081:8081"
    links:
        - mongo
    environment: 
        - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017
  user-postgres-database:
    image: postgres
    container_name: user-postgres-db
    volumes:
      - ./postgres-init.sql:/docker-entrypoint-initdb.d/postgres-init.sql
    environment:
      POSTGRES_PASSWORD: "naovoufalar"
    ports:
      - "5432:5432"